version: "3"
services:
  db:
    image: postgres
    container_name: "how_postgres"
    environment:
      - POSTGRES_USER=iara
      - POSTGRES_PASSWORD=iara
      - POSTGRES_DB=desafio_01
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data/